### ISSUE TITLE
The following classes could not be instantiated:

### ISSUE THREAD

**Issue by BrutalCSkakan** [eluleci/FlatUI#36]
Getting this error when im trying to add a <com.cengalabs.flatui.views.FlatTextView
- com.cengalabs.flatui.views.FlatTextView
  (Open Class, Show Exception)

Tip: Use View.isInEditMode() in your code or show sample data when shown in the IDE

How do i fix this?

**Comment by corentindesfarges** [comment]
Same issue for me.

**Comment by BrutalCSkakan** [comment]
The author seems to answer other issues, what's up with not answering this one..

**Comment by mygoda** [comment]
哦哦

**Comment by RahulSDeshpande** [comment]
Same error here.. :(

Here is the logcat output:

```
E/AndroidRuntime(1796): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.cengalabs.flatui.sample/com.cengalabs.flatui.sample.MainActivity}: android.view.InflateException: Binary XML file line #28: Error inflating class com.cengalabs.flatui.views.FlatTextView

E/AndroidRuntime(1130):  Caused by: java.lang.NoClassDefFoundError:com.cengalabs.flatui.R$styleable

E/AndroidRuntime(1130):  at com.cengalabs.flatui.views.FlatTextView.init(FlatTextView.java:65)
E/AndroidRuntime(1130):  at com.cengalabs.flatui.views.FlatTextView.<init>(FlatTextView.java:37)
```

Has anyone found any fix for this ??

Is it because we are using **v7-appcompat-lib** ??
