### ISSUE TITLE
Runtime exception when using FlatUI on Android 4.0.4

### ISSUE THREAD

**Issue by aagam-shah** [eluleci/FlatUI#40]
```
01-07 13:38:10.096  10485-10485/com.pingbits E/AndroidRuntime﹕ FATAL EXCEPTION: main
java.lang.UnsupportedOperationException
        at android.view.GLES20Canvas.clipPath(GLES20Canvas.java:429)
        at com.cengalabs.flatui.TouchEffectAnimator.onDraw(TouchEffectAnimator.java:139)
        at com.cengalabs.flatui.views.FlatButton.onDraw(FlatButton.java:61)
        at android.view.View.draw(View.java:11054)
        at android.view.View.getDisplayList(View.java:10493)
        at android.view.ViewGroup.drawChild(ViewGroup.java:2958)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2596)
        at android.view.View.draw(View.java:11057)
        at android.view.View.getDisplayList(View.java:10493)
        at android.view.ViewGroup.drawChild(ViewGroup.java:2958)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2596)
        at android.view.View.getDisplayList(View.java:10491)
        at android.view.ViewGroup.drawChild(ViewGroup.java:2958)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2596)
        at android.view.View.getDisplayList(View.java:10491)
        at android.view.ViewGroup.drawChild(ViewGroup.java:2958)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2596)
        at android.view.View.getDisplayList(View.java:10491)
        at android.view.ViewGroup.drawChild(ViewGroup.java:2958)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2596)
        at android.view.View.draw(View.java:11057)
        at android.widget.FrameLayout.draw(FrameLayout.java:463)
        at android.view.View.getDisplayList(View.java:10493)
        at android.view.ViewGroup.drawChild(ViewGroup.java:2958)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2596)
        at android.view.View.getDisplayList(View.java:10491)
        at android.view.ViewGroup.drawChild(ViewGroup.java:2958)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2596)
        at android.view.View.getDisplayList(View.java:10491)
        at android.view.ViewGroup.drawChild(ViewGroup.java:2958)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2596)
        at android.view.View.getDisplayList(View.java:10491)
        at android.view.ViewGroup.drawChild(ViewGroup.java:2958)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2596)
        at android.view.View.draw(View.java:11057)
        at android.widget.FrameLayout.draw(FrameLayout.java:463)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2145)
        at android.view.View.getDisplayList(View.java:10493)
        at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:880)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:1911)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1635)
        at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2455)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:4424)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:817)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
        at dalvik.system.NativeStart.main(Native Method)
```

**Comment by frankfang668** [comment]
Face the same problem :(
The answer should be below:
http://stackoverflow.com/questions/13676059/android-unsupportedoperationexception-at-canvas-clippath
